version: "3.9"

services:
  front:
    build:
      context: ./tvshow-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://back:8080
    depends_on:
      - back
    networks:
      - app-network

  back:
    build:
      context: ./tvshow-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./tvshow-backend/src/main/resources:/app/src/main/resources
    environment:
      SPRING_APPLICATION_NAME: TV Show Backend
      APP_FILEPATH: /app/src/main/resources/tvtitles.txt
      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/src/main/resources/database/tvshowsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_OPENFEIGN: DEBUG
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
